language: node_js
node_js:
  - "10"
  
install:
  - npm install
script:
  - npm run build
  - ls
deploy:
  target-branch: gh-pages
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./build
  on:
    branch: master